version: '3'
services:
    openfire:
        container_name: SrvMensajeria
        image: sameersbn/openfire
        ports:
            - "9090:9090"
            - "5222:5222"
        networks:
            sri:
                ipv4_address: 192.168.200.2

networks:
  sri:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.200.0/24
