version: '3'
services:
    nginx:
        container_name: SrvProxyWeb
        image: francisjgarcia/nginx
        ports:
            - '80:80'
        networks:
            sri:
                ipv4_address: 192.168.200.2

networks:
  sri:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.200.0/24
