apiVersion: v1  
kind: ReplicationController  
metadata:  
  name: ghost
  labels:
    purpose: francisjgarcia.ml
spec:  
  replicas: 1
  template:
    metadata:
      labels:
        app: ghost
        purpose: francisjgarcia.ml
    spec:
      containers:
      - name: ghost
        image: ghost:latest
        resources:
          limits:
            cpu: 200m
            memory: 50Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 2368
        volumeMounts:
          # name must match the volume name below
          - name: ghost-data
            mountPath: "/var/lib/ghost"
      volumes:
        - name: ghost-data
          persistentVolumeClaim:
            claimName: nfs-cluster