apiVersion: v1  
kind: Service  
metadata:  
  labels:
    name: ghost-lb
    purpose: francisjgarcia.ml
  name: ghost-lb
spec:  
  ports:
    - port: 2368
  selector:
    app: ghost
  type: LoadBalancer