version: '3'
services:
    postfix:
        container_name: SrvCorreoServer
        image: francisjgarcia/postfixserver
        ports:
            - "25:25"
        networks:
            sri:
                ipv4_address: 192.168.200.2

networks:
  sri:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.200.0/24
