version: '3'
services:
    mysql:
        container_name: SrvMySQL
        image: francisjgarcia/mysql
        ports:
            - '3306:3306'
        networks:
            sri:
                ipv4_address: 192.168.200.2

networks:
  sri:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.200.0/24
